version: '3.8'

services:
  channel_service:
    build: .
    ports:
      - "5000:5000"  # Пробрасываем порт 8000 из контейнера на хост
    environment:
      - DEBUG=False  # Пример переменной окружения
      # Тестовый режим: работаем без внешних серверов транспортного уровня
      - TEST_MODE=true
    volumes:
      - .:/appCL  # Для разработки: синхронизация кода